/**
 * CV Viewer
 * CV Viewer.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: neilje123@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Qualification } from './qualification';


export interface EducationInstitution { 
    institution?: string;
    startDate?: string;
    endDate?: string;
    qualifications?: Array<Qualification>;
}
