/**
 * CV Viewer
 * CV Viewer.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: neilje123@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { KeySkill } from './keySkill';
import { RecentWorkExperienceItem } from './recentWorkExperienceItem';


export interface Header { 
    dateOfBirth?: string;
    currentPosition?: string;
    addressLines?: Array<string>;
    phoneMobile?: string;
    emailAddress?: string;
    maritalStatus?: string;
    nationality?: string;
    recentWorkExperience?: Array<RecentWorkExperienceItem>;
    keySkills?: Array<KeySkill>;
}
